### ISSUE TITLE
Generate a summary report

### ISSUE THREAD

**Issue by ceastman-ibm** [snyk/snyk-to-html#22]
The current report has too many details to be easily readable. Could their be a summary report option that only had a few key entries like the following:

Severity:
Vulnerable module:
Introduced through:
Remediation:

And have the report sorted by Severity with highest first.

**Comment by lili2311** [comment]
Thank you for raising this, this would make a great candidate for an open source contribution. I will mark it as such :)

**Comment by lili2311** [comment]
- [ ] add a new `summary` mode to pass to `snyk-to-html` lib
- [ ] `snyk test --file=A --file=B` in summary mode correctly returns summary for both project

**Comment by sfat** [comment]
<img width="1645" alt="Screenshot 2020-01-14 at 22 35 08" src="https://user-images.githubusercontent.com/442744/72380538-51414500-371e-11ea-9a8c-904cbc7e9da8.png">

The parameter can be passed via `-s` or `--summary`. I've removed the `Overview` and `Details` sections and left only Remediation.

I've also changed the name of the title from `Snyk test report` to `Snyk test summary`. Is this something desirable or should I leave that as-is? Or is there a suggestion to naming it differently?

Is there something  else that needs to be added/removed?

**Comment by lili2311** [comment]
Are the references useful in this mode? Wonder if just a link to the vuln page would be enough.

**Comment by sfat** [comment]
I can remove the references section, sure. I didn't have any reason to keep it, didn't know what do keep/remove 😄

**Comment by lili2311** [comment]
what do you think @ceastman-ibm? Would this be valuable to keep for you?

**Comment by lili2311** [comment]
@ceastman-ibm please try this out and let us know how you get on, this is now released.
