### ISSUE TITLE
Unexpected token in JSON at position 0

### ISSUE THREAD

**Issue by serjebulavsky** [snyk/snyk-to-html#56]
Hello, i'm trying out this addition to snyk on my test project, an i've encountered this error: 
```
 SyntaxError: Unexpected token � in JSON at position 0
    at parse (<anonymous>)
```
Command: `snyk-to-html -i results.json -o results.html`
Json is autogenerated by `snyk test --json`, i haven't changed it somehow and seems correct. 
results.json file: https://gist.github.com/serjebulavsky/f1ef98973892615c99ff7999fd6f45c4

**Comment by lili2311** [comment]
👋 Are you seeing this on the latest version of CLI? Possibly related? https://github.com/snyk/snyk/issues/845

**Comment by serjebulavsky** [comment]
```
[feature/snyk-spike ≡ +5 ~1 -0 !]> snyk test --json > results.json | snyk-to-html -i results.json -o results.html
SyntaxError: Unexpected token � in JSON at position 0
    at parse (<anonymous>)
[feature/snyk-spike ≡ +5 ~1 -0 !]> snyk --version
1.246.0
```

**Comment by serjebulavsky** [comment]
@lili2311 Just updated it again, the same result :(

**Comment by lili2311** [comment]
- What OS are you on?
- could you also try  `snyk test --json 2>error | more` and share what you see here?

The snipped you shared of the JSON did not have any unexpected chars

**Comment by serjebulavsky** [comment]
@lili2311 Windows 10, build 17763, no errors, just same json with results of check, it is quite long.

**Comment by lili2311** [comment]
This implied it is the very first character `Unexpected token � in JSON at position 0`

**Comment by lili2311** [comment]
Do you get the same issue if you skip writing the file and pipe straight into the snyk-to-html `snyk test --json | snyk-to-html`?

**Comment by serjebulavsky** [comment]
@lili2311 piping directly to snyk-to-html are just hangs after start, so i'm guessing it is hanging because of an error.

**Comment by lili2311** [comment]
Sorry I gave you a slightly wrong command, please see usage here: https://github.com/snyk/snyk-to-html 

Try with `snyk test --json | snyk-to-html -o results.html` as it suggests and let me know what that does?

**Comment by serjebulavsky** [comment]
@lili2311 Sorry for long anwer! But unfortunately, it is the same. 
![image](https://user-images.githubusercontent.com/1502886/69128583-3916c600-0adf-11ea-94f9-43454d135e69.png)

**Comment by lili2311** [comment]
Please try with the latest version of `snyk-to-html` `1.8.0`  we have release some error handling improvements.
